NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS
MINUTES = 60 * SECONDS
HOURS = 60 * MINUTES

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 25.5
MINING_REWARD_INPUT = { 'address': '*--official-mining-reward--*' }
